if (!window['google']) {
window['google'] = {};
}
if (!window['google']['loader']) {
window['google']['loader'] = {};
google.loader.ServiceBase = 'http://www.google.com/uds';
google.loader.GoogleApisBase = 'http://ajax.googleapis.com/ajax';
google.loader.ApiKey = 'notsupplied';
google.loader.KeyVerified = true;
google.loader.LoadFailure = false;
google.loader.Secure = false;
google.loader.ClientLocation = {"latitude":12.967,"longitude":77.583,"address":{"city":"Bengaluru","region":"Karnataka","country":"India","country_code":"IN"}};
google.loader.AdditionalParams = '';
(function() {var e=false,g=null,h=true,i=encodeURIComponent,j=window,k=google,l=undefined,m=document;function o(a,b){return a.load=b}var p="push",q="length",t="prototype",u="setTimeout",v="replace",w="charAt",x="loader",y="substring",z="ServiceBase",B="toLowerCase";function C(a){if(a in D)return D[a];return D[a]=navigator.userAgent[B]().indexOf(a)!=-1}var D={};function E(){return C("safari")||C("konqueror")}function F(a,b){var c=function(){};c.prototype=b[t];a.M=b[t];a.prototype=new c}
function G(a,b){var c=a.A||[];c=c.concat(Array[t].slice.call(arguments,2));if(typeof a.p!="undefined")b=a.p;if(typeof a.o!="undefined")a=a.o;var d=function(){var f=c.concat(Array[t].slice.call(arguments));return a.apply(b,f)};d.A=c;d.p=b;d.o=a;return d}function H(a){var b=new Error(a);b.toString=function(){return this.message};return b}function I(a,b){var c=a.split(/\./),d=j;for(var f=0;f<c[q]-1;f++){d[c[f]]||(d[c[f]]={});d=d[c[f]]}d[c[c[q]-1]]=b}function J(a,b,c){a[b]=c}var aa=aa||{};
if(!K)var K=I;if(!ba)var ba=J;k[x].q={};K("google.loader.callbacks",k[x].q);var L={},M={};k[x].eval={};K("google.loader.eval",k[x].eval);o(k,function(a,b,c){var d=L[":"+a];if(d){if(c&&!c.language&&c.locale)c.language=c.locale;var f=c&&c.callback!=g;if(f&&!d.n())throw H("Module: '"+a+"' must be loaded before DOM onLoad!");else if(f)d.j(b,c)?j[u](c.callback,0):d.load(b,c);else d.j(b,c)||d.load(b,c)}else throw H("Module: '"+a+"' not found!");});K("google.load",k.load);k.H=function(a,b){b?ca(a):O(j,"load",a)};
K("google.setOnLoadCallback",k.H);function O(a,b,c){if(a.addEventListener)a.addEventListener(b,c,e);else if(a.attachEvent)a.attachEvent("on"+b,c);else{var d=a["on"+b];a["on"+b]=d!=g?da([c,d]):c}}function da(a){return function(){for(var b=0;b<a[q];b++)a[b]()}}var P=[];function ca(a){if(P[q]==0){O(j,"load",Q);if(!C("msie")&&!E()&&C("mozilla")||j.L)j.addEventListener("DOMContentLoaded",Q,e);else if(C("msie")){j[u](R,10);m.attachEvent("onreadystatechange",S)}else E()&&j[u](T,10)}P[p](a)}
function R(){try{P[q]>0&&m.documentElement.doScroll("left")}catch(a){j[u](R,10);return}Q()}var U={loaded:h,complete:h};function S(){if(U[m.readyState]){m.detachEvent("onreadystatechange",S);Q()}}function T(){if(U[m.readyState])Q();else P[q]>0&&j[u](T,10)}function Q(){for(var a=0;a<P[q];a++)P[a]();P.length=0}
k[x].c=function(a,b,c){if(c){var d;if(a=="script"){d=m.createElement("script");d.type="text/javascript";d.src=b}else if(a=="css"){d=m.createElement("link");d.type="text/css";d.href=b;d.rel="stylesheet"}var f=m.getElementsByTagName("head")[0];f||(f=m.body.parentNode.appendChild(m.createElement("head")));f.appendChild(d)}else if(a=="script")m.write('<script src="'+b+'" type="text/javascript"><\/script>');else a=="css"&&m.write('<link href="'+b+'" type="text/css" rel="stylesheet"></link>')};
K("google.loader.writeLoadTag",k[x].c);k[x].F=function(a){M=a};K("google.loader.rfm",k[x].F);k[x].G=function(a){for(var b in a)if(typeof b=="string"&&b&&b[w](0)==":"&&!L[b])L[b]=new V(b[y](1),a[b])};K("google.loader.rpl",k[x].G);k[x].loaded=function(a){L[":"+a.module].h(a)};K("google.loader.loaded",k[x].loaded);I("google_exportSymbol",I);I("google_exportProperty",J);function W(a){this.a=a;this.l={};this.b={};this.i=h}
W[t].e=function(a,b){var c="";if(b!=l){if(b.language!=l)c+="&hl="+i(b.language);if(b.nocss!=l)c+="&output="+i("nocss="+b.nocss);if(b.nooldnames!=l)c+="&nooldnames="+i(b.nooldnames);if(b.packages!=l)c+="&packages="+i(b.packages);if(b.callback!=g)c+="&async=2";if(b.other_params!=l)c+="&"+b.other_params}if(!this.i){if(k[this.a]&&k[this.a].JSHash)c+="&sig="+i(k[this.a].JSHash);var d=[];for(var f in this.l)f[w](0)==":"&&d[p](f[y](1));for(var f in this.b)f[w](0)==":"&&d[p](f[y](1));c+="&have="+i(d.join(","))}return k[x][z]+
"/?file="+this.a+"&v="+a+k[x].AdditionalParams+c};W[t].s=function(a){var b=g;if(a)b=a.packages;var c=g;if(b)if(typeof b=="string")c=[a.packages];else if(b[q]){c=[];for(var d=0;d<b[q];d++)typeof b[d]=="string"&&c[p](b[d][v](/^\s*|\s*$/,"")[B]())}c||(c=["default"]);var f=[];for(var d=0;d<c[q];d++)this.l[":"+c[d]]||f[p](c[d]);return f};
o(W[t],function(a,b){var c=this.s(b),d=b&&b.callback!=g;if(d)var f=new X(b.callback);var r=[];for(var s=c[q]-1;s>=0;s--){var n=c[s];d&&f.B(n);if(this.b[":"+n]){c.splice(s,1);d&&this.b[":"+n][p](f)}else r[p](n)}if(c[q]){if(b&&b.packages)b.packages=c.sort().join(",");if(!b&&M[":"+this.a]!=g&&M[":"+this.a].versions[":"+a]!=g&&!k[x].AdditionalParams&&this.i){var A=M[":"+this.a];k[this.a]=k[this.a]||{};for(var N in A.properties)if(N&&N[w](0)==":")k[this.a][N[y](1)]=A.properties[N];k[x].c("script",k[x][z]+
A.path+A.js,d);A.css&&k[x].c("css",k[x][z]+A.path+A.css,d)}else k[x].c("script",this.e(a,b),d);if(this.i)this.i=e;for(var s=0;s<r[q];s++){var n=r[s];this.b[":"+n]=[];d&&this.b[":"+n][p](f)}}});W[t].h=function(a){for(var b=0;b<a.components[q];b++){this.l[":"+a.components[b]]=h;var c=this.b[":"+a.components[b]];if(c){for(var d=0;d<c[q];d++)c[d].D(a.components[b]);delete this.b[":"+a.components[b]]}}Y("hl",this.a)};W[t].j=function(a,b){return this.s(b)[q]==0};W[t].n=function(){return h};
function X(a){this.C=a;this.k={};this.m=0}X[t].B=function(a){this.m++;this.k[":"+a]=h};X[t].D=function(a){if(this.k[":"+a]){this.k[":"+a]=e;this.m--;this.m==0&&j[u](this.C,0)}};function Z(a,b,c,d,f,r,s,n){this.a=a;this.w=b;this.J=c;this.u=d;this.z=f;this.I=r;this.v=s||{};this.r=this.f=e;this.g=[];this.t=typeof n=="string"?n:n?b:g;this.K=n;k[x].q[this.a]=G(this.h,this)}F(Z,W);o(Z[t],function(a,b){var c=b&&b.callback!=g;if(c){this.g[p](b.callback);b.callback="google.loader.callbacks."+this.a}else this.f=h;k[x].c("script",this.e(a,b),c)});Z[t].j=function(a,b){return b&&b.callback!=g?this.r:this.f};
Z[t].h=function(){this.r=h;for(var a=0;a<this.g[q];a++)j[u](this.g[a],0);this.g=[]};
Z[t].e=function(a,b){var c="";if(this.u!=g)c+="&"+this.u+"="+i(k[x].ApiKey);if(this.z!=g)c+="&"+this.z+"="+i(a);var d=k[x].Secure,f;if(d&&this.t)f=this.t;else{f=this.w;d=e}if(b!=g)for(var r in b)if(this.v[":"+r]!=g){var s=b[r],n=this.v[":"+r];c+=typeof n=="string"?"&"+n+"="+i(s):"&"+n(s)}else if(r=="other_params")c+="&"+b[r];else if(r=="base_domain"){f=this.w;d=e;f=f[v](/^[^\/]*/,b[r])}k[this.a]={};if(!this.J&&c!="")c="?"+c[y](1);Y("el",this.a);return(d?"https":"http")+"://"+f+c};Z[t].n=function(){return this.I};function V(a,b){this.a=a;this.d=b;this.f=e}F(V,W);o(V[t],function(a,b){this.f=h;k[x].c("script",this.e(a,b),e)});V[t].j=function(){return this.f};V[t].h=function(){};V[t].e=function(a,b){if(!this.d.versions[":"+a]){if(this.d.aliases){var c=this.d.aliases[":"+a];if(c)a=c}if(!this.d.versions[":"+a])throw H("Module: '"+this.a+"' with version '"+a+"' not found!");}var d=k[x].GoogleApisBase+"/libs/"+this.a+"/"+a+"/"+this.d.versions[":"+a][b&&b.uncompressed?"uncompressed":"compressed"];Y("el",this.a);return d};
V[t].n=function(){return e};var ea=e,$=[],ga=function(){if(!ea){O(j,"unload",fa);ea=h}},Y=function(a,b,c){ga();if(c){if(!k[x].Secure&&(!k[x].Options||k[x].Options.csi===e)){a=a[B]()[v](/[^a-z0-9_.]+/g,"_");b=b[B]()[v](/[^a-z0-9_.]+/g,"_");var d="http://csi.gstatic.com/csi?s=uds&v=2&action="+i(a)+"&it="+i(b);j[u](G(ha,g,d),10000)}}else{$[p]("r"+$[q]+"="+i(a+(b?"|"+b:"")));j[u](fa,$[q]>5?0:15000)}},fa=function(){if($[q]){(new Image).src=k[x][z]+"/stats?"+$.join("&")+"&nocache="+Number(new Date);$.length=0}},ha=function(a){(new Image).src=
a};I("google.loader.recordStat",Y);L[":search"]=new W("search");L[":feeds"]=new W("feeds");L[":language"]=new W("language");L[":elements"]=new W("elements");L[":ads"]=new W("ads");L[":maps"]=new Z("maps","maps.google.com/maps?file=googleapi",h,"key","v",h,{":language":"hl",":callback":function(a){return"callback="+i(a)+"&async=2"}},"maps-api-ssl.google.com/maps?file=googleapi");L[":gdata"]=new W("gdata");L[":sharing"]=new Z("sharing","www.google.com/s2/sharing/js",e,"key","v",e,{":locale":"hl"});
L[":annotations"]=new Z("annotations","www.google.com/reviews/scripts/annotations_bootstrap.js",e,"key","v",h,{":language":"hl",":country":"gl",":callback":"callback"});L[":visualization"]=new W("visualization");L[":books"]=new Z("books","books.google.com/books/api.js",e,"key","v",h,{":language":"hl",":callback":"callback"});L[":earth"]=new W("earth");

}) ();google.loader.rfm({":feeds":{"versions":{":1":"1",":1.0":"1"},"path":"/api/feeds/1.0/a883ea4e4fee6493f8d9160a2de00a5b/","js":"default+en.I.js","css":"default.css","properties":{":JSHash":"a883ea4e4fee6493f8d9160a2de00a5b",":Version":"1.0"}},":search":{"versions":{":1":"1",":1.0":"1"},"path":"/api/search/1.0/2ef92627ebd5e8ac619ec04330343d27/","js":"default+en.I.js","css":"default.css","properties":{":JSHash":"2ef92627ebd5e8ac619ec04330343d27",":NoOldNames":false,":Version":"1.0"}},":language":{"versions":{":1":"1",":1.0":"1"},"path":"/api/language/1.0/da2b456bb541f01cda0db146a5dd6f26/","js":"default+en.I.js","properties":{":JSHash":"da2b456bb541f01cda0db146a5dd6f26",":Version":"1.0"}},":earth":{"versions":{":1":"1",":1.0":"1"},"path":"/api/earth/1.0/38fe800a6509664ee4edaa397931e6e0/","js":"default.I.js","properties":{":JSHash":"38fe800a6509664ee4edaa397931e6e0",":Version":"1.0"}},":ads":{"versions":{":1":"1",":1.0":"1"},"path":"/api/ads/1.0/57def315a657eea8fac36aa21d7311f0/","js":"default.I.js","properties":{":JSHash":"57def315a657eea8fac36aa21d7311f0",":Version":"1.0"}}});
google.loader.rpl({":scriptaculous":{"versions":{":1.8.2":{"uncompressed":"scriptaculous.js","compressed":"scriptaculous.js"},":1.8.1":{"uncompressed":"scriptaculous.js","compressed":"scriptaculous.js"}},"aliases":{":1.8":"1.8.2",":1":"1.8.2"}},":yui":{"versions":{":2.6.0":{"uncompressed":"build/yuiloader/yuiloader.js","compressed":"build/yuiloader/yuiloader-min.js"}},"aliases":{":2":"2.6.0",":2.6":"2.6.0"}},":swfobject":{"versions":{":2.1":{"uncompressed":"swfobject_src.js","compressed":"swfobject.js"}},"aliases":{":2":"2.1"}},":mootools":{"versions":{":1.2.1":{"uncompressed":"mootools.js","compressed":"mootools-yui-compressed.js"},":1.11":{"uncompressed":"mootools.js","compressed":"mootools-yui-compressed.js"}},"aliases":{":1":"1.11"}},":jqueryui":{"versions":{":1.5.3":{"uncompressed":"jquery-ui.js","compressed":"jquery-ui.min.js"},":1.5.2":{"uncompressed":"jquery-ui.js","compressed":"jquery-ui.min.js"}},"aliases":{":1":"1.5.3",":1.5":"1.5.3"}},":prototype":{"versions":{":1.6.0.2":{"uncompressed":"prototype.js","compressed":"prototype.js"},":1.6.0.3":{"uncompressed":"prototype.js","compressed":"prototype.js"}},"aliases":{":1":"1.6.0.3",":1.6":"1.6.0.3"}},":jquery":{"versions":{":1.2.3":{"uncompressed":"jquery.js","compressed":"jquery.min.js"},":1.3.1":{"uncompressed":"jquery.js","compressed":"jquery.min.js"},":1.3.0":{"uncompressed":"jquery.js","compressed":"jquery.min.js"},":1.2.6":{"uncompressed":"jquery.js","compressed":"jquery.min.js"}},"aliases":{":1":"1.3.1",":1.3":"1.3.1",":1.2":"1.2.6"}},":dojo":{"versions":{":1.2.3":{"uncompressed":"dojo/dojo.xd.js.uncompressed.js","compressed":"dojo/dojo.xd.js"},":1.1.1":{"uncompressed":"dojo/dojo.xd.js.uncompressed.js","compressed":"dojo/dojo.xd.js"},":1.2.0":{"uncompressed":"dojo/dojo.xd.js.uncompressed.js","compressed":"dojo/dojo.xd.js"}},"aliases":{":1":"1.2.3",":1.2":"1.2.3",":1.1":"1.1.1"}}});
}
